// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Log severity level. Mirrors the native mars/xlog `TLogLevel`.
enum XlogLevel: Int {
  case verbose = 0
  case debug = 1
  case info = 2
  case warning = 3
  case error = 4
  case fatal = 5
  case none = 6
}

/// Appender write mode.
enum XlogMode: Int {
  /// Asynchronous write (default, best performance).
  case async = 0
  /// Synchronous write.
  case sync = 1
}

/// Compression algorithm used for log content.
enum XlogCompressMode: Int {
  /// zlib compression (default).
  case zlib = 0
  /// zstd compression.
  case zstd = 1
}

/// Configuration used to open the global xlog appender.
///
/// Only the initialization/configuration surface is exposed through pigeon.
/// Writing log entries is handled separately through Dart FFI.
///
/// Generated class from Pigeon that represents data sent in messages.
struct XlogConfig {
  /// Memory-mapped cache directory (e.g. context.cacheDir on Android).
  var cacheDir: String
  /// Directory the log files are written to.
  var logDir: String
  /// Log file name prefix.
  var namePrefix: String
  /// Minimum level to emit.
  var level: XlogLevel
  /// Appender write mode.
  var mode: XlogMode
  /// Encryption public key. Empty string disables encryption.
  var pubKey: String
  /// Compression algorithm for log content.
  var compressMode: XlogCompressMode
  /// Compression level (0-9). 0 means no compression; 6 is the native default.
  var compressLevel: Int64
  /// Number of days to keep cached (mmap) logs. 0 uses the native default.
  var cacheDays: Int64
  /// Whether logs are also mirrored to the system console (logcat / Xcode).
  var consoleLogEnabled: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> XlogConfig? {
    let cacheDir = pigeonVar_list[0] as! String
    let logDir = pigeonVar_list[1] as! String
    let namePrefix = pigeonVar_list[2] as! String
    let level = pigeonVar_list[3] as! XlogLevel
    let mode = pigeonVar_list[4] as! XlogMode
    let pubKey = pigeonVar_list[5] as! String
    let compressMode = pigeonVar_list[6] as! XlogCompressMode
    let compressLevel = pigeonVar_list[7] as! Int64
    let cacheDays = pigeonVar_list[8] as! Int64
    let consoleLogEnabled = pigeonVar_list[9] as! Bool

    return XlogConfig(
      cacheDir: cacheDir,
      logDir: logDir,
      namePrefix: namePrefix,
      level: level,
      mode: mode,
      pubKey: pubKey,
      compressMode: compressMode,
      compressLevel: compressLevel,
      cacheDays: cacheDays,
      consoleLogEnabled: consoleLogEnabled
    )
  }
  func toList() -> [Any?] {
    return [
      cacheDir,
      logDir,
      namePrefix,
      level,
      mode,
      pubKey,
      compressMode,
      compressLevel,
      cacheDays,
      consoleLogEnabled,
    ]
  }
}

private class XlogConfigApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return XlogLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return XlogMode(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return XlogCompressMode(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return XlogConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class XlogConfigApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? XlogLevel {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? XlogMode {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? XlogCompressMode {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? XlogConfig {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class XlogConfigApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return XlogConfigApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return XlogConfigApiPigeonCodecWriter(data: data)
  }
}

class XlogConfigApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = XlogConfigApiPigeonCodec(readerWriter: XlogConfigApiPigeonCodecReaderWriter())
}

/// Initialization and configuration API for xlog.
///
/// Implemented natively (Kotlin / Swift) and called from Dart. This lets a
/// pure-Flutter app initialize xlog from Dart, while a hybrid app may instead
/// initialize natively and skip these calls entirely.
///
/// Log writing is NOT part of this API; it goes through Dart FFI.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol XlogConfigApi {
  /// Opens the global log appender with [config].
  func initialize(config: XlogConfig) throws
  /// Flushes buffered logs to disk. When [sync] is true, blocks until the
  /// write completes (do not call on the UI thread).
  func flush(sync: Bool) throws
  /// Closes the appender and releases resources.
  func close() throws
  /// Changes the global minimum log level at runtime.
  func setLevel(level: XlogLevel) throws
  /// Returns the current global minimum log level.
  func getLevel() throws -> XlogLevel
  /// Enables or disables mirroring logs to the system console.
  func setConsoleLogEnabled(enabled: Bool) throws
  /// Switches the appender write mode at runtime. Must be called after
  /// [initialize].
  func setAppenderMode(mode: XlogMode) throws
  /// Sets the maximum size in bytes of a single log file; the appender rolls
  /// to a new file once exceeded. Must be called after [initialize].
  func setMaxFileSize(maxBytes: Int64) throws
  /// Sets the maximum retention time in seconds for log files; older files are
  /// deleted automatically. Must be called after [initialize].
  func setMaxAliveSeconds(seconds: Int64) throws
  /// Returns the prefixes of all currently open log instances.
  func instancePrefixes() throws -> [String]
  /// Whether a log instance with [prefix] is currently open.
  func hasInstance(prefix: String) throws -> Bool
  /// Flushes the instance's buffered logs. When [sync] is true, blocks until
  /// the write completes (do not call on the UI thread).
  func flushInstance(prefix: String, sync: Bool) throws
  /// Returns the instance's current minimum log level.
  func getInstanceLevel(prefix: String) throws -> XlogLevel
  /// Enables or disables mirroring the instance's logs to the system console.
  func setInstanceConsoleLogEnabled(prefix: String, enabled: Bool) throws
  /// Closes the instance and releases its resources.
  func closeInstance(prefix: String) throws
  /// Returns the instance's log file paths over the last [timespanDays] days
  /// counting back from today (0 = today only). Useful for uploading logs.
  func getInstanceLogFiles(prefix: String, timespanDays: Int64) throws -> [String]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class XlogConfigApiSetup {
  static var codec: FlutterStandardMessageCodec { XlogConfigApiPigeonCodec.shared }
  /// Sets up an instance of `XlogConfigApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: XlogConfigApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Opens the global log appender with [config].
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! XlogConfig
        do {
          try api.initialize(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Flushes buffered logs to disk. When [sync] is true, blocks until the
    /// write completes (do not call on the UI thread).
    let flushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.flush\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let syncArg = args[0] as! Bool
        do {
          try api.flush(sync: syncArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      flushChannel.setMessageHandler(nil)
    }
    /// Closes the appender and releases resources.
    let closeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.close\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChannel.setMessageHandler { _, reply in
        do {
          try api.close()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeChannel.setMessageHandler(nil)
    }
    /// Changes the global minimum log level at runtime.
    let setLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.setLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! XlogLevel
        do {
          try api.setLevel(level: levelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLevelChannel.setMessageHandler(nil)
    }
    /// Returns the current global minimum log level.
    let getLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.getLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLevelChannel.setMessageHandler(nil)
    }
    /// Enables or disables mirroring logs to the system console.
    let setConsoleLogEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.setConsoleLogEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setConsoleLogEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setConsoleLogEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setConsoleLogEnabledChannel.setMessageHandler(nil)
    }
    /// Switches the appender write mode at runtime. Must be called after
    /// [initialize].
    let setAppenderModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.setAppenderMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAppenderModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modeArg = args[0] as! XlogMode
        do {
          try api.setAppenderMode(mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAppenderModeChannel.setMessageHandler(nil)
    }
    /// Sets the maximum size in bytes of a single log file; the appender rolls
    /// to a new file once exceeded. Must be called after [initialize].
    let setMaxFileSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.setMaxFileSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMaxFileSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let maxBytesArg = args[0] as! Int64
        do {
          try api.setMaxFileSize(maxBytes: maxBytesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMaxFileSizeChannel.setMessageHandler(nil)
    }
    /// Sets the maximum retention time in seconds for log files; older files are
    /// deleted automatically. Must be called after [initialize].
    let setMaxAliveSecondsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.setMaxAliveSeconds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMaxAliveSecondsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let secondsArg = args[0] as! Int64
        do {
          try api.setMaxAliveSeconds(seconds: secondsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMaxAliveSecondsChannel.setMessageHandler(nil)
    }
    /// Returns the prefixes of all currently open log instances.
    let instancePrefixesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.instancePrefixes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      instancePrefixesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.instancePrefixes()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      instancePrefixesChannel.setMessageHandler(nil)
    }
    /// Whether a log instance with [prefix] is currently open.
    let hasInstanceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.hasInstance\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasInstanceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let prefixArg = args[0] as! String
        do {
          let result = try api.hasInstance(prefix: prefixArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasInstanceChannel.setMessageHandler(nil)
    }
    /// Flushes the instance's buffered logs. When [sync] is true, blocks until
    /// the write completes (do not call on the UI thread).
    let flushInstanceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.flushInstance\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushInstanceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let prefixArg = args[0] as! String
        let syncArg = args[1] as! Bool
        do {
          try api.flushInstance(prefix: prefixArg, sync: syncArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      flushInstanceChannel.setMessageHandler(nil)
    }
    /// Returns the instance's current minimum log level.
    let getInstanceLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.getInstanceLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInstanceLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let prefixArg = args[0] as! String
        do {
          let result = try api.getInstanceLevel(prefix: prefixArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getInstanceLevelChannel.setMessageHandler(nil)
    }
    /// Enables or disables mirroring the instance's logs to the system console.
    let setInstanceConsoleLogEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.setInstanceConsoleLogEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setInstanceConsoleLogEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let prefixArg = args[0] as! String
        let enabledArg = args[1] as! Bool
        do {
          try api.setInstanceConsoleLogEnabled(prefix: prefixArg, enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setInstanceConsoleLogEnabledChannel.setMessageHandler(nil)
    }
    /// Closes the instance and releases its resources.
    let closeInstanceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.closeInstance\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeInstanceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let prefixArg = args[0] as! String
        do {
          try api.closeInstance(prefix: prefixArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeInstanceChannel.setMessageHandler(nil)
    }
    /// Returns the instance's log file paths over the last [timespanDays] days
    /// counting back from today (0 = today only). Useful for uploading logs.
    let getInstanceLogFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xlog.XlogConfigApi.getInstanceLogFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInstanceLogFilesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let prefixArg = args[0] as! String
        let timespanDaysArg = args[1] as! Int64
        do {
          let result = try api.getInstanceLogFiles(prefix: prefixArg, timespanDays: timespanDaysArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getInstanceLogFilesChannel.setMessageHandler(nil)
    }
  }
}
