// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package xyz.bczl.xlog

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Log severity level. Mirrors the native mars/xlog `TLogLevel`. */
enum class XlogLevel(val raw: Int) {
  VERBOSE(0),
  DEBUG(1),
  INFO(2),
  WARNING(3),
  ERROR(4),
  FATAL(5),
  NONE(6);

  companion object {
    fun ofRaw(raw: Int): XlogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Appender write mode. */
enum class XlogMode(val raw: Int) {
  /** Asynchronous write (default, best performance). */
  ASYNC(0),
  /** Synchronous write. */
  SYNC(1);

  companion object {
    fun ofRaw(raw: Int): XlogMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Compression algorithm used for log content. */
enum class XlogCompressMode(val raw: Int) {
  /** zlib compression (default). */
  ZLIB(0),
  /** zstd compression. */
  ZSTD(1);

  companion object {
    fun ofRaw(raw: Int): XlogCompressMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Configuration used to open the global xlog appender.
 *
 * Only the initialization/configuration surface is exposed through pigeon.
 * Writing log entries is handled separately through Dart FFI.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class XlogConfig (
  /** Memory-mapped cache directory (e.g. context.cacheDir on Android). */
  val cacheDir: String,
  /** Directory the log files are written to. */
  val logDir: String,
  /** Log file name prefix. */
  val namePrefix: String,
  /** Minimum level to emit. */
  val level: XlogLevel,
  /** Appender write mode. */
  val mode: XlogMode,
  /** Encryption public key. Empty string disables encryption. */
  val pubKey: String,
  /** Compression algorithm for log content. */
  val compressMode: XlogCompressMode,
  /** Compression level (0-9). 0 means no compression; 6 is the native default. */
  val compressLevel: Long,
  /** Number of days to keep cached (mmap) logs. 0 uses the native default. */
  val cacheDays: Long,
  /** Whether logs are also mirrored to the system console (logcat / Xcode). */
  val consoleLogEnabled: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): XlogConfig {
      val cacheDir = pigeonVar_list[0] as String
      val logDir = pigeonVar_list[1] as String
      val namePrefix = pigeonVar_list[2] as String
      val level = pigeonVar_list[3] as XlogLevel
      val mode = pigeonVar_list[4] as XlogMode
      val pubKey = pigeonVar_list[5] as String
      val compressMode = pigeonVar_list[6] as XlogCompressMode
      val compressLevel = pigeonVar_list[7] as Long
      val cacheDays = pigeonVar_list[8] as Long
      val consoleLogEnabled = pigeonVar_list[9] as Boolean
      return XlogConfig(cacheDir, logDir, namePrefix, level, mode, pubKey, compressMode, compressLevel, cacheDays, consoleLogEnabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cacheDir,
      logDir,
      namePrefix,
      level,
      mode,
      pubKey,
      compressMode,
      compressLevel,
      cacheDays,
      consoleLogEnabled,
    )
  }
}
private open class XlogConfigApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          XlogLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          XlogMode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          XlogCompressMode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          XlogConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is XlogLevel -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is XlogMode -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is XlogCompressMode -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is XlogConfig -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Initialization and configuration API for xlog.
 *
 * Implemented natively (Kotlin / Swift) and called from Dart. This lets a
 * pure-Flutter app initialize xlog from Dart, while a hybrid app may instead
 * initialize natively and skip these calls entirely.
 *
 * Log writing is NOT part of this API; it goes through Dart FFI.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface XlogConfigApi {
  /** Opens the global log appender with [config]. */
  fun initialize(config: XlogConfig)
  /**
   * Flushes buffered logs to disk. When [sync] is true, blocks until the
   * write completes (do not call on the UI thread).
   */
  fun flush(sync: Boolean)
  /** Closes the appender and releases resources. */
  fun close()
  /** Changes the global minimum log level at runtime. */
  fun setLevel(level: XlogLevel)
  /** Returns the current global minimum log level. */
  fun getLevel(): XlogLevel
  /** Enables or disables mirroring logs to the system console. */
  fun setConsoleLogEnabled(enabled: Boolean)
  /**
   * Switches the appender write mode at runtime. Must be called after
   * [initialize].
   */
  fun setAppenderMode(mode: XlogMode)
  /**
   * Sets the maximum size in bytes of a single log file; the appender rolls
   * to a new file once exceeded. Must be called after [initialize].
   */
  fun setMaxFileSize(maxBytes: Long)
  /**
   * Sets the maximum retention time in seconds for log files; older files are
   * deleted automatically. Must be called after [initialize].
   */
  fun setMaxAliveSeconds(seconds: Long)
  /** Returns the prefixes of all currently open log instances. */
  fun instancePrefixes(): List<String>
  /** Whether a log instance with [prefix] is currently open. */
  fun hasInstance(prefix: String): Boolean
  /**
   * Flushes the instance's buffered logs. When [sync] is true, blocks until
   * the write completes (do not call on the UI thread).
   */
  fun flushInstance(prefix: String, sync: Boolean)
  /** Returns the instance's current minimum log level. */
  fun getInstanceLevel(prefix: String): XlogLevel
  /** Enables or disables mirroring the instance's logs to the system console. */
  fun setInstanceConsoleLogEnabled(prefix: String, enabled: Boolean)
  /** Closes the instance and releases its resources. */
  fun closeInstance(prefix: String)
  /**
   * Returns the instance's log file paths over the last [timespanDays] days
   * counting back from today (0 = today only). Useful for uploading logs.
   */
  fun getInstanceLogFiles(prefix: String, timespanDays: Long): List<String>

  companion object {
    /** The codec used by XlogConfigApi. */
    val codec: MessageCodec<Any?> by lazy {
      XlogConfigApiPigeonCodec()
    }
    /** Sets up an instance of `XlogConfigApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: XlogConfigApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as XlogConfig
            val wrapped: List<Any?> = try {
              api.initialize(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.flush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val syncArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.flush(syncArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.close()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.setLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as XlogLevel
            val wrapped: List<Any?> = try {
              api.setLevel(levelArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.getLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getLevel())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.setConsoleLogEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setConsoleLogEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.setAppenderMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as XlogMode
            val wrapped: List<Any?> = try {
              api.setAppenderMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.setMaxFileSize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val maxBytesArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setMaxFileSize(maxBytesArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.setMaxAliveSeconds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val secondsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setMaxAliveSeconds(secondsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.instancePrefixes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.instancePrefixes())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.hasInstance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.hasInstance(prefixArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.flushInstance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            val syncArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.flushInstance(prefixArg, syncArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.getInstanceLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getInstanceLevel(prefixArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.setInstanceConsoleLogEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            val enabledArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setInstanceConsoleLogEnabled(prefixArg, enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.closeInstance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.closeInstance(prefixArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xlog.XlogConfigApi.getInstanceLogFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            val timespanDaysArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getInstanceLogFiles(prefixArg, timespanDaysArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
